tags = {
	'CS' : {
	'Machine Learning' : ['pattern recognition','unsupervised learning','algorithm','automaton','probability','statistics','machine learning','artificial intelligence',
	'arthur samuel','comber','electromechanical','device','machine tool','perceptron','mathematical model','computational',
	'statistics','mathematical','optimization','spam filter','optical character recognition','ocr','cycloscope','bot','learning to rank',
	'generator','computer vision','vision''machine translation','enginery','equipment','data mining','backpropagation','intelligence',],	

	'Artifical Intelligence' : ['artificial', 'neural', 'network', 'machine', 'learning', 'knowledge', 
	'representation','automated', 'planning', 'and', 'scheduling', 'machine', 'perception', 'robotics', 'logic','alphago', 'artificial',
	 'general', 'intelligence', 'game', 'theory', 'natural', 'language', 'processing', 'psychology', 'herbert', 'a.', 'simon', 'reinforcement',
	  'learning', 'information', 'theory', 'marvin', 'minsky', 'operations', 'research', 'speech', 'recognition', 'computer', 'science', 'moore', 
	  's', 'law', 'computer', 'vision', 'optimization', 'mathematics', 'mind','neuroscience', 'cybernetic', 'ai', 'natural', 'language', 
	  'understanding', 'economics', 'autonomous', 'car', 'ai', 'winter', 'technological', 'singularity', 'big', 'data', 'mary', 'shelley', 'karel',
	   'čapek', 'warren', 'mccullouch', 'walter', 'pitts', 'allen', 'newell', 'john', 'mccarthy', 'massachusetts', 'institute', 'of', 'technology',
	    'probability', 'expert', 'system', 'utility', 'fifth', 'generation', 'computer', 'data', 'mining', 'deep', 'learning', 'artificial', 'selection', 'bayesian', 'inference', 'support', 'vector', 'machine', 'k-nearest', 'neighbor', 'algorithm', 'cybernetics', 'description', 'logic', 'mit', 'evolutionary', 'algorithms', 'swarm', 'intelligence', 'unsupervised', 'learning', 'supervised', 'learning', 'machine', 'translation', 'sentiment', 'analysis', 'moravec', 'paradox', 'hans', 'moravec', 'intelligence', 'machine', 'developmental', 'robotics', 'chess', 'linguistics','cognitive', 'science','heuristics','statistics', 'watson','turing-complete', 'heuristic','semantics','tic-tac-toe', 'intelligent', 'agent'],
	
	'Data Science': ['statistics', 'knowledge', 'data', 'computer', 'science', 'predictive', 'modelling', 'mathematics', 'buzzword', 'jim', 'gray', 'harvard', 'business', 'review', 'business', 'analytics', 'nate', 'silver', 'big', 'data', 'interdisciplinary', 'american', 'statistical', 'association', 'data', 'mining', 'information', 'science', 'turing', 'award', 'datalogy', 'discipline', 'empirical', 'research', 'basic', 'research', 'information', 'explosion', 'forbes', 'business', 'intelligence', 'hans', 'rosling', 'signal', 'processing', 'telemetry', 'format', 'formatting', 'buffer', 'track', 'baud', 'drive', 'editor', 'protocol', 'latency', 'overhead', 'router', 'tracked', 'tracking', 'tracks', 'allocation', 'block', 'operation', 'bps', 'cache', 'clear', 'processor', 'icon', 'graphics', 'printer', 'queue', 'export', 'dumping', 'dump', 'code', 'cleared', 'instruction', 'scanning', 'intelligent', 'scanned', 'informatics', 'hit', 'hardware', 'filter', 'field', 'documented', 'download', 'emulate', 'encode', 'encoding', 'coding', 'file', 'filtered', 'filtering', 'fix', 'float', 'garbage', 'host', 'import', 'compress', 'compressing', 'compression', 'core', 'batch', 'corrupt', 'corrupted', 'cpu', 'crash', 'demanding', 'demand', 'browser', 'disk', 'cached', 'documentation', 'peter', 'naur', 'methodology', 'prasanta', 'chandra', 'mahalanobis', 'buffing', 'eprom', 'positioner', 'overwrite', 'flied', 'bionics', 'delimiter', 'coring', 'interdisciplinarity', 'jeff', 'hammerbacher', 'general', 'assembly', 'analytics', 'the', 'data', 'incubator', 'university', 'of', 'essex', 'theory', 'machine', 'learning', 'paradigm', 'computing', 'software', 'developer', 'software', 'engineer', 'data', 'processing'],
	
	'Compilers' : ['parser', 'computer', 'program', 'cpu', 'interpreter', 'source', 'code', 'programming', 'language', 'machine', 'code', 'computer', 'science', 'assembler', 'debugger', 'fortran', 'translator', 'cobol', 'algorithm', 'emulation', 'assembly', 'language', 'program', 'compiling', 'program', 'translation', 'debug', 'programme', 'programmer', 'encyclopedist', 'software', 'firmware', 'code', 'interface', 'compile', 'runtime', 'c', 'compiler', 'api', 'macros', 'subroutine', 'scheduler', 'c++', 'emacs', 'microprocessor', 'kernel', 'decompiler', 'rewriting', 'high-level', 'programming', 'language', 'debugging', 'linker', 'binary', 'code', 'bytecode', 'machine', 'language', 'lexical', 'analysis', 'jit', 'ibm', 'llvm', 'semantic', 'analysis', 'code', 'generation', 'compiler', 'correctness', 'pascal', 'disassembler', 'basic', 'executable', 'compiler', 'optimization', 'lexicographer', 'author', 'computing', 'writer', 'spyware', 'programmable', 'adware', 'vm', 'malware', 'compilers', 'metaprogram', 'parsing', 'cross-compiler', 'softlifting', 'playbill', 'telnet', 'teleprogramming', 'teleprogrammed', 'nonprogramming', 'encyclopaedist', 'lexicologist', 'counterprogramming', 'metaprogramming', 'preprogram', 'optimizer', 'login', 'computer', 'hardware', 'techie', 'subprogram', 'compiler-compiler', 'hackathon', 'applet', 'optimizations', 'kludge'],
	
	'Cryptography' : ['cryptanalysis', 'encryption', 'cipher', 'authentication', 'steganography', 'rsa', 'password', 'information', 'ciphertext', 'decryption', 'algorithm', 'combinatorics', 'computer', 'symmetric-key', 'algorithm', 'advanced', 'encryption', 'standard', 'elliptic', 'curve', 'cryptography', 'one-time', 'pad', 'integer', 'factorization', 'data', 'encryption', 'standard', 'mathematics', 'science', 'code', 'coding', 'world', 'war', 'ii', 'cryptology', 'cryptanalytics', 'computer', 'science', 'encoding', 'electrical', 'engineering', 'decipherment', 'decoding', 'plaintext', 'electronic', 'commerce', 'cryptographic', 'discrete', 'logarithm', 'caesar', 'cipher', 'cryptogram', 'key', 'algorithms', 'espionage', 'ciphers', 'cryptosystem', 'rotor', 'machine', 'quantum', 'physics', 'software', 'digital', 'signature', 'interactive', 'proof', 'system', 'ancient', 'greece', 'elgamal', 'encryption', 'kerckhoffs', 'principle', 'claude', 'shannon', 'information', 'theory', 'signature', 'research', 'adversary', 'physics', 'nonsense', 'eavesdropper', 'md5', 'sedition', 'writing', '-logy', 'confidentiality', 'non-repudiation', 'colloquial', 'secrecy', 'communications', 'spy', 'diplomat', 'computational', 'complexity', 'theory', 'recoding', 'suetonius', 'number', 'theory', 'egypt', 'sparta', 'secret', 'writing', 'herodotus', 'cryptographic', 'engineering', 'security', 'engineering', 'rivest-shamir-adleman', 'polymath', 'puzzle', 'crypto', 'public-key', 'encrypting', 'encrypt', 'encrypted', 'ancient', 'greek', 'language', 'romanization', 'of', 'ancient', 'greek', 'grille', 'computation', 'secure', 'communication', 'atbash', 'communications', 'protocol', 'information', 'security', 'data', 'integrity', 'mems', 'quantitative', 'microdot', 'linkage', 'kamasutra', 'optimization', 'computational', 'associative', 'quantum', 'vātsyāyana', 'communication', 'science', 'linear', 'codification', 'credit', 'card', 'chip', 'bit', 'algebraic', 'digital', 'currencies', 'diode', 'numerical', 'topology', 'analytic', 'pivot', 'semiotic', 'architectures', 'military', 'communications', 'al-kindi', 'asymmetric', 'argumentation'],
	
	'Operating Systems' : ['unix', 'kernel', 'linux', 'ibm', 'system', 'software', 'device', 'driver', 'computer', 'program', 'computer', 'software', 'software', 'microsoft', 'windows', 'disk', 'operating', 'system', 'android', 'computer', 'network', 'protected', 'mode', 'freebsd', 'apple', 'inc.', 'computer', 'architecture', 'nextstep', 'ms-dos', 'windows', 'nt', 'mac', 'os', 'master', 'control', 'program', 'os', 'paging', 'interrupt', 'amigaos', 'next', 'bsd', 'netbsd', 'openbsd', 'graphical', 'user', 'interface', 'digital', 'equipment', 'corporation', 'computer', 'multitasking', 'real-time', 'operating', 'system', 'linus', 'torvalds', 'free', 'software', 'unix-like', 'dos', 'infrastructure', 'computer', 'science', 'platform', 'machine', 'code', 'time-sharing', '32-bit', 'os', 'x', 'unix', 'system', 'unix', 'operating', 'system', 'central', 'processing', 'unit', 'data', 'os/360', 'control', 'embedded', 'system', 'resident', 'monitor', 'runtime', 'library', 'operate', 'assembly', 'language', 'b5000', 'batch', 'processing', 'hardware', 'effective', 'openvms', 'firmware', 'server', 'methodology', 'input', 'posix', 'steve', 'jobs', 'open', 'source', 'shell', 'linux', 'kernel', 'system', 'computer', 'network', 'supercomputer', 'ios', 'virtualization', 'the', 'open', 'group', 'windows', 'supervisor', 'package', 'computing', 'berkeley', 'software', 'distribution', 'atlas', 'linker', 'systems', 'multi-tasking', '16-bit', 'google', 'multi-user', 'file', 'system', 'unikernel', 'existing', 'scope'],
	
	'Networks' : ['internet', 'server', 'router', 'world', 'wide', 'web', 'node', 'lan', 'intranet', 'computer', 'wide', 'area', 'network', 'firewall', 'modem', 'computer', 'science', 'local', 'area', 'network', 'ethernet', 'network', 'bridge', 'extranet', 'host', 'computer', 'hardware', 'transmission', 'control', 'protocol', 'internet', 'protocol', 'software', 'data', 'web', 'hardware', 'network', 'telecommunications', 'cyberspace', 'www', 'computing', 'bandwidth', 'security', 'system', 'client', 'information', 'age', 'database', 'osi', 'model', 'latency', 'circuit', 'switching', 'network', 'switch', 'internet', 'protocol', 'suite', 'routing', 'digital', 'peer-to-peer', 'g.hn', 'phone', 'cybernetwork', 'multinetwork', 'multinetworked', 'video', 'personal', 'computer', 'cybernetic', 'telecommuter', 'netzine', 'telnet', 'cyberinteraction', 'cyberintrusion', 'cyberterrorism', 'cable', 'cybersociology', 'cyber', 'communications', 'protocol', 'ieee', '802.11', 'ieee', '802.3', 'network', 'address', 'cyberia', 'cybertechnology', 'cybersavvy', 'cybersystem', 'ip', 'address', 'cyberjunkie', 'sneakernet', 'quality', 'of', 'service', 'cyberpsychology', 'cyberjargon', 'minicomputer', 'cpu', 'login', 'cybersuicide', 'processor', 'cyberphilosophy', 'microcomputer', 'softmodem', 'microprocessor', 'system', 'gateway', 'motherboard', 'vm', 'mainframe', 'downloader', 'supercomputer', 'hostmaster', 'stream', 'video', 'precomputer', 'anticomputer', 'computerist', 'compunications', 'computerology', 'neurocomputer', 'telecomputer', 'appender', 'nanocomputer', 'noncomputer', 'computeritis', 'bios', 'computerologist', 'computernik', 'computerdom', 'compy', 'puter', 'bridging', 'teletype', 'ibook', 'information', 'superhighway', 'screensaver', 'cyberdating', 'computerbased', 'computerism', 'compute', 'cybergeneration', 'pda', 'uploader', 'wave', 'clip', 'wardialer', 'computerlike', 'computercide', 'pessimize', 'cyberfuture', 'computerize', 'pseudocode', 'logon', 'predictor', 'access', 'internet', 'cyberinformation', 'database', 'management', 'system', 'computer', 'aid', 'design', 'antivirus'],
	
	'DBMS'  : ['cryptanalysis', 'encryption', 'cipher', 'authentication', 'steganography', 'rsa', 'password', 'information', 'ciphertext', 'decryption', 'algorithm', 'combinatorics', 'computer', 'symmetric-key', 'algorithm', 'advanced', 'encryption', 'standard', 'elliptic', 'curve', 'cryptography', 'one-time', 'pad', 'integer', 'factorization', 'data', 'encryption', 'standard', 'mathematics', 'science', 'code', 'coding', 'world', 'war', 'ii', 'cryptology', 'cryptanalytics', 'computer', 'science', 'encoding', 'electrical', 'engineering', 'decipherment', 'decoding', 'plaintext', 'electronic', 'commerce', 'cryptographic', 'discrete', 'logarithm', 'caesar', 'cipher', 'cryptogram', 'key', 'algorithms', 'espionage', 'ciphers', 'cryptosystem', 'rotor', 'machine', 'quantum', 'physics', 'software', 'digital', 'signature', 'interactive', 'proof', 'system', 'ancient', 'greece', 'elgamal', 'encryption', 'kerckhoffs', 'principle', 'claude', 'shannon', 'information', 'theory', 'signature', 'research', 'adversary', 'physics', 'nonsense', 'eavesdropper', 'md5', 'sedition', 'writing', '-logy', 'confidentiality', 'non-repudiation', 'colloquial', 'secrecy', 'communications', 'spy', 'diplomat', 'computational', 'complexity', 'theory', 'recoding', 'suetonius', 'number', 'theory', 'egypt', 'sparta', 'secret', 'writing', 'herodotus', 'cryptographic', 'engineering', 'security', 'engineering', 'rivest-shamir-adleman', 'polymath', 'puzzle', 'crypto', 'public-key', 'encrypting', 'encrypt', 'encrypted', 'ancient', 'greek', 'language', 'romanization', 'of', 'ancient', 'greek', 'grille', 'computation', 'secure', 'communication', 'atbash', 'communications', 'protocol', 'information', 'security', 'data', 'integrity', 'mems', 'quantitative', 'microdot', 'linkage', 'kamasutra', 'optimization', 'computational', 'associative', 'quantum', 'vātsyāyana', 'communication', 'science', 'linear', 'codification', 'credit', 'card', 'chip', 'bit', 'algebraic', 'digital', 'currencies', 'diode', 'numerical', 'topology', 'analytic', 'pivot', 'semiotic', 'architectures', 'military', 'communications', 'al-kindi', 'asymmetric', 'argumentation'],
	
	'Software Engineering' : ['computer', 'engineering', 'programmer', 'software', 'program', 'debug', 'program', 'code', 'hardware', 'interface', 'computer', 'science', 'technical', 'support', 'ieee', 'swebok', 'software', 'engineering', 'institute', 'computer', 'programming', 'ieee', 'computer', 'society', 'spyware', 'firmware', 'malware', 'certified', 'software', 'development', 'professional', 'vm', 'programmable', 'abstraction', 'telnet', 'debugger', 'fortran', 'parser', 'algol', 'login', 'compiler', 'cobol', 'british', 'computer', 'society', 'adware', 'assembler', 'softlifting', 'modularity', 'techie', 'hackathon', 'nonprogramming', 'metaprogramming', 'writing', 'uploader', 'pessimize', 'downloader', 'microprocessor', 'processor', 'screensaver', 'cpu', 'wardialer', 'incrementor', 'pseudocode', 'antivirus', 'shareware', 'teleprogramming', 'minicomputer', 'metaprogram', 'playbill', 'softmodem', 'professional', 'engineer', 'optimizer', 'algorithm', 'applet', 'bloatware', 'teleprogrammed', 'gnome', 'microcomputer', 'crossgrade', 'motherboard', 'counterprogramming', 'interpreter', 'multitask', 'preprogram', 'cybernetic', 'bios', 'multiprogramming', 'virtualize', 'ssh', 'compute', 'groupware', 'bot', 'intranet', 'pda', 'encode', 'portability', 'freeware', 'subprogram', 'teletype', 'appender', 'multinetwork', 'multinetworked', 'cyberintrusion', 'telecomputer', 'kludge', 'bitness', 'cybernetwork', 'cybersystem', 'hostmaster', 'meatware', 'precomputer', 'keygen', 'anticomputer', 'computerist', 'netzine', 'uninstall', 'cybersociology', 'telecommuter', 'cybertechnology', 'computerology', 'compy', 'puter', 'cyberpsychology', 'ibook', 'cyberinteraction', 'software', 'design', 'computerbased', 'computernik', 'nanocomputer', 'computerologist', 'noncomputer', 'computeritis', 'rootkit', 'multiload'],
	
	'Digital Electronics' : ['electronic', 'circuit', 'integrated', 'circuit', 'combinational', 'logic', 'noise', 'logic', 'gate', 'binary', 'number', 'system', 'vacuum', 'tube', 'transistor', 'truth', 'table', 'cd-rom', 'transistors', 'electronics', 'bit', 'z3', 'electronic', 'design', 'automation', 'printed', 'circuit', 'board', 'computer', 'hertz', 'flip-flop', 'silicon', 'scalability', 'redundancy', 'amplifier', 'tuner', 'digital', 'signal', 'radio', 'analog', 'circuits', 'analog', 'signal', 'engineering', 'tolerance', 'fidelity', 'path', 'loss', 'quine–mccluskey', 'algorithm', 'gottfried', 'wilhelm', 'leibniz', 'george', 'boole', 'charles', 'sanders', 'peirce', 'lee', 'de', 'forest', 'fleming', 'valve', 'and', 'gate', 'ludwig', 'wittgenstein', 'tractatus', 'logico-philosophicus', 'walther', 'bothe', 'coincidence', 'circuit', 'microcontroller', 'nobel', 'prize', 'mechanical', 'computer', 'analog', 'computer', 'world', 'war', 'ii', 'digital', 'data', 'personal', 'computer', 'electromechanical', 'computer', 'konrad', 'zuse', 'computer', 'programming', 'john', 'ambrose', 'fleming', 'bipolar', 'junction', 'transistor', 'university', 'of', 'manchester', 'state', 'machine', 'tom', 'kilburn', 'transistor', 'computer', 'texas', 'instruments', 'jack', 'kilby', 'semiconductor', 'material', 'integrated', 'circuit', 'design', 'core', 'binary', 'dss', 'arbiter', 'signal', 'chain', 'number', 'software', 'radio', 'quantization', 'error', 'nyquist-shannon', 'sampling', 'theorem', 'cliff', 'effect', 'automaton', 'parity', 'bit', 'abacus', 'error', 'correction', 'and', 'detection', 'error', 'detection', 'and', 'correction', 'linear', 'pulse', 'code', 'modulation', 'coring', 'debounce', 'audio', 'compression', 'memory', 'boolean', 'logic', 'vhdl', 'ascii', 'bandwidth', 'sensor', 'asl', 'midi', 'ten', 'sector', 'scanner', 'scale', 'rings', 'ranking', 'ranked', 'file', 'bits', 'octave', 'multimedia', 'clock', 'email', 'cpu', 'pixel', 'hypertext', 'shot', 'colon', 'jack', 'jacked', 'jacking', 'jacks', 'hdtv', 'poke', 'verilog', 'thermionic', 'valves', 'cdr', 'jpeg', 'jukebox', 'atm', 'lcd', 'analog', 'audacity', 'mainframe', 'manual', 'metadata', 'microarchitecture', 'microcomputer', 'minicomputer', 'modem', 'aliasing', 'age'],
	
	'Computer architecture' : ['hardware', 'computer', 'cpu', 'supercomputer', 'computer', 'science', 'computerize', 'neural', 'network', 'laptop', 'techie', 'mac', 'risc', 'information', 'age', 'cisc', 'computer', 'engineering', 'processor', 'minicomputer', 'microprocessor', 'motherboard', 'microcomputer', 'cyberintrusion', 'computing', 'cybersystem', 'vm', 'neurocomputer', 'telnet', 'softmodem', 'anticomputer', 'precomputer', 'computerology', 'computerist', 'puter', 'computerologist', 'nanocomputer', 'noncomputer', 'computerdom', 'computernik', 'computeritis', 'multinetworked', 'multinetwork', 'compy', 'mainframe', 'cybernetic', 'hostmaster', 'bios', 'computerbased', 'cybernetwork', 'screensaver', 'ibook', 'computerism', 'cybersociology', 'compute', 'telecommuter', 'cybersavvy', 'pseudocode', 'cyberinteraction', 'computerlike', 'appender', 'cyberterrorism', 'computercide', 'cyberjunkie', 'telecomputer', 'cyberpsychology', 'pda', 'cybertechnology', 'login', 'cyberjargon', 'pessimize', 'netzine', 'wardialer', 'downloader', 'uploader', 'computer', 'aid', 'design', 'digital', 'computer', 'antivirus', 'cyberphilosophy', 'organize', 'information', 'computable', 'computational', 'teletype', 'biocomputing', 'digital', 'communication', 'wave', 'clip', 'cybergeneration', 'data', 'converter', 'intranet', 'computer', 'circuit', 'cybersuicide', 'hackathon', 'peripheral', 'virtualize', 'in', 'observatory', 'central', 'process', 'unit', 'dumb', 'terminal', 'turing', 'machine', 'word', 'process', 'metaprogramming', 'access', 'internet', 'gnome', 'incrementor', 'analog', 'computer', 'programmable', 'graphic', 'card', 'machinima', 'computer', 'system', 'compunications', 'rootkit', 'cyber', 'memex', 'machine', 'code', 'configuration', 'section', 'download', 'manager', 'logon', 'automation', 'stream', 'video', 'surf', 'internet', 'uninstall', 'von', 'neumann', 'machine', 'cyberfuture', 'database', 'management', 'system', 'predictor', 'cyberdating', 'security', 'system', 'command', 'line', 'interpreter', 'extranet', 'data', 'process', 'peripheral', 'brain', 'at', 'internet', 'cafe', 'diskette', 'chiclet', 'keyboard', 'web', 'server', 'process', 'information', 'sneakernet', 'memory', 'chip']
	}

}

# for keys,values in tags.items():
# 	print(keys)
# 	for key,value in values:
# 		print(key,value)
    
    # print(values)